version: "3.1"

services:
  # Serviço que irá rodar o node
  api-enafood:
    build: . # lembrar de rodar docker-compose up --build --renew-anon-volumes para rebuildar imagem
    container_name: enafood_api
    restart: unless-stopped
    volumes:
      - ./backend/src:/app/
      - ./backend/package.json:/app/package.json
      - /app/node_modules 
    depends_on:
      - db
    ports:
      - 3000:3000
    environment:
      DB_USER: root
      DB_PASSWORD: db_password
      DB_HOST: enafood_db
      DB_PORT: 27017
      DB_NAME: enafood_database

  db:
    image: mongo
    container_name: enafood_db
    restart: unless-stopped
    ports:
      # Expõe a porta padrão do banco de dados
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: some_root_password
      # MONGO_INITDB_DATABASE This variable allows you to specify 
      # the name of a database to be used for creation scripts in 
      # /docker-entrypoint-initdb.d/*.js.
      # MongoDB is fundamentally designed for "create on first use",
      # so if you do not insert data with your JavaScript files, 
      # then no database is created.
      MONGO_INITDB_DATABASE: enafood_database
      DB_USER: root
      DB_PASSWORD: db_password
      DB_NAME: enafood_database
    volumes:
      - mongodb_data:/data/db
      - ./backend/mongo_init.js:/docker-entrypoint-initdb.d/mongo_init.js:ro


volumes:
  mongodb_data: